// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State struct {
	Streams              []*Stream `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetStreams() []*Stream {
	if m != nil {
		return m.Streams
	}
	return nil
}

type Stream struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Application          string   `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	AuthKey              string   `protobuf:"bytes,4,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	AuthExpire           int64    `protobuf:"varint,5,opt,name=auth_expire,json=authExpire,proto3" json:"auth_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Stream) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Stream) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *Stream) GetAuthExpire() int64 {
	if m != nil {
		return m.AuthExpire
	}
	return 0
}

func init() {
	proto.RegisterType((*State)(nil), "storage.State")
	proto.RegisterType((*Stream)(nil), "storage.Stream")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4e, 0x86, 0x30,
	0x10, 0x46, 0x53, 0xf9, 0x7f, 0xc0, 0x21, 0xc6, 0x64, 0x16, 0xa6, 0xae, 0x6c, 0x58, 0xd5, 0x0d,
	0x0b, 0x3c, 0x83, 0x2b, 0x77, 0xe5, 0x00, 0x66, 0x24, 0x13, 0x6d, 0x14, 0xda, 0x94, 0xd1, 0xc8,
	0x35, 0x3c, 0xb1, 0xa1, 0x42, 0xe2, 0x6e, 0xde, 0x7b, 0xf9, 0x16, 0x03, 0x57, 0x8b, 0x84, 0x44,
	0xaf, 0xdc, 0xc5, 0x14, 0x24, 0x60, 0xb5, 0x63, 0xdb, 0xc3, 0x79, 0x10, 0x12, 0xc6, 0x7b, 0xa8,
	0x16, 0x49, 0x4c, 0xd3, 0xa2, 0x95, 0x29, 0x6c, 0xd3, 0x5f, 0x77, 0xc7, 0x64, 0xc8, 0xde, 0x1d,
	0xbd, 0xfd, 0x51, 0x50, 0xfe, 0x39, 0x44, 0x38, 0xcd, 0x34, 0xb1, 0x56, 0x46, 0xd9, 0x4b, 0x97,
	0x6f, 0xbc, 0x81, 0x92, 0x46, 0xf1, 0x5f, 0xac, 0x2f, 0x8c, 0xb2, 0xb5, 0xdb, 0x09, 0x0d, 0x34,
	0x14, 0xe3, 0x87, 0x1f, 0x49, 0x7c, 0x98, 0x75, 0x91, 0x27, 0xff, 0x15, 0xde, 0x42, 0x4d, 0x9f,
	0xf2, 0xf6, 0xfc, 0xce, 0xab, 0x3e, 0xe5, 0x5c, 0x6d, 0xfc, 0xc4, 0x2b, 0xde, 0x41, 0x93, 0x13,
	0x7f, 0x47, 0x9f, 0x58, 0x9f, 0x8d, 0xb2, 0x85, 0x83, 0x4d, 0x3d, 0x66, 0xf3, 0x52, 0xe6, 0xc7,
	0x1e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xb0, 0x81, 0xc1, 0xe9, 0x00, 0x00, 0x00,
}
